services:
  # Backend FastAPI
  - type: web
    name: grc-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false

databases:
  # PostgreSQL Database
  - name: grc-db
    databaseName: grc_compliance
    user: grc_user
    plan: free
